---
title: "Cytek Management"
#output: html_notebook
---

# Load Libraries

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(chron)
```

# Read in data

Read in csv files for galender and user/lab key

```{r}
cal_data <- read.csv('cytek_google_calendar.csv')
lab_key <- read.csv('lab_key.csv')
```

# Data wrangling

First I need to tidy this data by separating the date into individual columns.

add :00 to times
convert times into new column
create use time column
remove NA values
 

```{r}
# Add :00 to all times for conversion
cal_data$start <- paste(cal_data$start, ':00')
cal_data$end <- paste(cal_data$end, ':00')

cal_data <- cal_data |>
  separate(date, into = c('month', 'day', 'year'), sep = '/' ) |>
  mutate(time_start = chron(times. = start)) |> #convert start times
  mutate(time_end = chron(times. = end)) |> # convert end times
  mutate(use_time = time_end - time_start) |>
  na.omit() 
```


Since the `name` column contains values entered by all the users, it is a mix of upper and lower case as well

```{r}
name.cleaner <- function(x, y) {
  gsub(x, x, y, ignore.case = TRUE)
}
```

```{r}
temp <- data.frame(name = unique(cal_data$name))
```




```{r}
temp_2 <- gsub('Ritz', 'Ritz', temp$name, ignore.case = TRUE)

temp_2 <- unique(temp_2)
```







